# config.yml
# Configuration for the OSMnx Dash Application

# Settings for osmnx library functions
osmnx_settings:
  # Tolerance for consolidating intersections (in meters).
  # Nodes within this distance of each other will be merged.
  # Larger values simplify complex interchanges more aggressively.
  consolidation_tolerance: 15
  # Network type to fetch (e.g., 'drive', 'walk', 'bike', 'all_private', 'all')
  network_type: "drive"

# Server settings for the Dash application
server_settings:
  host: "0.0.0.0"
  port: 8050
  debug: True # Set to False in production

# Paths for data files
data_paths:
  output_directory: "./data" # Directory where GeoJSON files will be saved
  polygon_geojson: "polygon.geojson" # Filename for the drawn polygon
  streets_geojson: "streets.geojson" # Filename for the processed streets